add notify method

diff --git a/dot_zshrc b/dot_zshrc
--- a/dot_zshrc
+++ b/dot_zshrc
@@ -114,6 +114,16 @@ toggledesktopicons() {
     killall Finder
 }
 
+notify() {
+    local exit_status=$?
+    if [ $exit_status -eq 0 ]; then
+        osascript -e 'display notification "Command completed successfully" with title "Terminal"'
+        say "Command finished successfully"
+    else
+        osascript -e 'display notification "Command failed with error code '$exit_status'" with title "Terminal Failure"'
+        say "Command failed"
+    fi
+}
 
 # demo db for lazysql
 alias dbd='lazysql "sqlite:///Users/adarsh/Personal/Pengvim/demo_database.db"'
